/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * orval-test API
 * API Documentation for the orval-test.
 * OpenAPI spec version: 0.0.0
 */
import type {
  PostAuthLogin200,
  PostAuthLogin401,
  PostAuthLoginBody
} from '../../models';


/**
 * Login to the BFF.
 */
export type postAuthLoginResponse200 = {
  data: PostAuthLogin200
  status: 200
}

export type postAuthLoginResponse401 = {
  data: PostAuthLogin401
  status: 401
}

export type postAuthLoginResponseSuccess = (postAuthLoginResponse200) & {
  headers: Headers;
};
export type postAuthLoginResponseError = (postAuthLoginResponse401) & {
  headers: Headers;
};

export type postAuthLoginResponse = (postAuthLoginResponseSuccess | postAuthLoginResponseError)

export const getPostAuthLoginUrl = () => {


  

  return `/auth/login`
}

export const postAuthLogin = async (postAuthLoginBody: PostAuthLoginBody, options?: RequestInit): Promise<postAuthLoginResponse> => {
  
  const res = await fetch(getPostAuthLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postAuthLoginBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postAuthLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postAuthLoginResponse
}
  

