/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * orval-test API
 * API Documentation for the orval-test.
 * OpenAPI spec version: 0.0.0
 */
import * as zod from 'zod';


/**
 * Login to the BFF.
 */
export const PostAuthLoginBody = zod.object({
  "email": zod.string(),
  "organisation": zod.string()
})

export const PostAuthLoginResponse = zod.object({
  "message": zod.string()
})

