/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * orval-test API
 * API Documentation for the orval-test.
 * OpenAPI spec version: 0.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  PostAuthLogin200
} from '../../models';


export const getPostAuthLoginResponseMock = (overrideResponse: Partial<Extract<PostAuthLogin200, object>> = {}): PostAuthLogin200 => ({message: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})


export const getPostAuthLoginMockHandler = (overrideResponse?: PostAuthLogin200 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PostAuthLogin200> | PostAuthLogin200), options?: RequestHandlerOptions) => {
  return http.post('*/auth/login', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostAuthLoginResponseMock(),
      { status: 200
      })
  }, options)
}
export const getAuthenticationMock = () => [
  getPostAuthLoginMockHandler()
]
