/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * orval-test API
 * API Documentation for the orval-test.
 * OpenAPI spec version: 0.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  DeleteSession200,
  GetSession200
} from '../../models';


export const getGetSessionResponseMock = (overrideResponse: Partial<Extract<GetSession200, object>> = {}): GetSession200 => ({email: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), company: faker.string.alpha({length: {min: 10, max: 20}}), avatar: faker.helpers.arrayElement([{src: faker.string.alpha({length: {min: 10, max: 20}}), alt: faker.string.alpha({length: {min: 10, max: 20}})}, undefined]), ...overrideResponse})

export const getDeleteSessionResponseMock = (overrideResponse: Partial<Extract<DeleteSession200, object>> = {}): DeleteSession200 => ({message: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})


export const getGetSessionMockHandler = (overrideResponse?: GetSession200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetSession200> | GetSession200), options?: RequestHandlerOptions) => {
  return http.get('*/session', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetSessionResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeleteSessionMockHandler = (overrideResponse?: DeleteSession200 | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<DeleteSession200> | DeleteSession200), options?: RequestHandlerOptions) => {
  return http.delete('*/session', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeleteSessionResponseMock(),
      { status: 200
      })
  }, options)
}
export const getSessionMock = () => [
  getGetSessionMockHandler(),
  getDeleteSessionMockHandler()
]
