/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * orval-test API
 * API Documentation for the orval-test.
 * OpenAPI spec version: 0.0.0
 */
import type {
  DeleteSession200,
  GetSession200
} from '../../models';

import { customInstance } from '../../mutator/custom-instance';

/**
 * Get public session data.
 */
export type getSessionResponse200 = {
  data: GetSession200
  status: 200
}

export type getSessionResponseSuccess = (getSessionResponse200) & {
  headers: Headers;
};
;

export type getSessionResponse = (getSessionResponseSuccess)

export const getGetSessionUrl = () => {


  

  return `http://localhost:3000/session`
}

export const getSession = async ( options?: RequestInit): Promise<getSessionResponse> => {
  
  return customInstance<getSessionResponse>(getGetSessionUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Delete the current user session.
 */
export type deleteSessionResponse200 = {
  data: DeleteSession200
  status: 200
}

export type deleteSessionResponseSuccess = (deleteSessionResponse200) & {
  headers: Headers;
};
;

export type deleteSessionResponse = (deleteSessionResponseSuccess)

export const getDeleteSessionUrl = () => {


  

  return `http://localhost:3000/session`
}

export const deleteSession = async ( options?: RequestInit): Promise<deleteSessionResponse> => {
  
  return customInstance<deleteSessionResponse>(getDeleteSessionUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

