/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * orval-test API
 * API Documentation for the orval-test.
 * OpenAPI spec version: 0.0.0
 */
import * as zod from 'zod';


/**
 * Get public session data.
 */
export const GetSessionResponse = zod.object({
  "email": zod.string(),
  "name": zod.string(),
  "company": zod.string(),
  "avatar": zod.object({
  "src": zod.string(),
  "alt": zod.string()
}).optional()
})

/**
 * Delete the current user session.
 */
export const DeleteSessionResponse = zod.object({
  "message": zod.string()
})

