/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * orval-test API
 * API Documentation for the orval-test.
 * OpenAPI spec version: 0.0.0
 */
import type {
  DeleteSession200,
  GetSession200
} from '../../models';


/**
 * Get public session data.
 */
export type getSessionResponse200 = {
  data: GetSession200
  status: 200
}

export type getSessionResponseSuccess = (getSessionResponse200) & {
  headers: Headers;
};
;

export type getSessionResponse = (getSessionResponseSuccess)

export const getGetSessionUrl = () => {


  

  return `/session`
}

export const getSession = async ( options?: RequestInit): Promise<getSessionResponse> => {
  
  const res = await fetch(getGetSessionUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getSessionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSessionResponse
}
  

/**
 * Delete the current user session.
 */
export type deleteSessionResponse200 = {
  data: DeleteSession200
  status: 200
}

export type deleteSessionResponseSuccess = (deleteSessionResponse200) & {
  headers: Headers;
};
;

export type deleteSessionResponse = (deleteSessionResponseSuccess)

export const getDeleteSessionUrl = () => {


  

  return `/session`
}

export const deleteSession = async ( options?: RequestInit): Promise<deleteSessionResponse> => {
  
  const res = await fetch(getDeleteSessionUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteSessionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteSessionResponse
}
  

