import type { ParsedOperation } from '../../../orval/types';
import { describe, expect, it } from 'vitest';
import { renderIndexFile, renderWrapperFile } from '../../../orval/templates';

const KEY_FACTORY = 'PETS_QUERY_KEYS';
const IMPORT_PATH = '@/api/endpoints/pets/pets';
const KEY_ROOT_SEGMENTS = ['pets'];

const queryOperation: ParsedOperation = {
  name: 'listPets',
  kind: 'query',
  params: [{ name: 'params', optional: true }],
};

const queryOperationWithMultipleParams: ParsedOperation = {
  name: 'searchPets',
  kind: 'query',
  params: [
    { name: 'params', optional: false },
    { name: 'fetchOptions', optional: true },
  ],
};

const mutationOperation: ParsedOperation = {
  name: 'createPets',
  kind: 'mutation',
  params: [
    { name: 'createPetsBody', optional: false },
    { name: 'fetchOptions', optional: true },
  ],
};

describe('renderWrapperFile', () => {
  describe('file header', () => {
    it('includes the generated-by comment', () => {
      const result = renderWrapperFile({
        endpointImportPath: IMPORT_PATH,
        operations: [queryOperation],
        queryKeyFactoryName: KEY_FACTORY,
        queryKeyRootSegments: KEY_ROOT_SEGMENTS,
      });
      expect(result).toContain('Generated by orval/generate-colada-wrappers.ts');
    });
  });

  describe('imports', () => {
    it('imports UseQueryOptions when query operations are present', () => {
      const result = renderWrapperFile({
        endpointImportPath: IMPORT_PATH,
        operations: [queryOperation],
        queryKeyFactoryName: KEY_FACTORY,
        queryKeyRootSegments: KEY_ROOT_SEGMENTS,
      });
      expect(result).toContain('import type { UseQueryOptions }');
    });

    it('does not import UseQueryOptions when only mutations are present', () => {
      const result = renderWrapperFile({
        endpointImportPath: IMPORT_PATH,
        operations: [mutationOperation],
        queryKeyFactoryName: KEY_FACTORY,
        queryKeyRootSegments: KEY_ROOT_SEGMENTS,
      });
      expect(result).not.toContain('UseQueryOptions');
    });

    it('imports useQuery when query operations are present', () => {
      const result = renderWrapperFile({
        endpointImportPath: IMPORT_PATH,
        operations: [queryOperation],
        queryKeyFactoryName: KEY_FACTORY,
        queryKeyRootSegments: KEY_ROOT_SEGMENTS,
      });
      expect(result).toContain('useQuery');
    });

    it('imports useMutation when mutation operations are present', () => {
      const result = renderWrapperFile({
        endpointImportPath: IMPORT_PATH,
        operations: [mutationOperation],
        queryKeyFactoryName: KEY_FACTORY,
        queryKeyRootSegments: KEY_ROOT_SEGMENTS,
      });
      expect(result).toContain('useMutation');
    });

    it('imports both hooks when both kinds of operations are present', () => {
      const result = renderWrapperFile({
        endpointImportPath: IMPORT_PATH,
        operations: [queryOperation, mutationOperation],
        queryKeyFactoryName: KEY_FACTORY,
        queryKeyRootSegments: KEY_ROOT_SEGMENTS,
      });
      expect(result).toContain('useMutation, useQuery');
    });

    it('imports all operations from the endpoint module', () => {
      const result = renderWrapperFile({
        endpointImportPath: IMPORT_PATH,
        operations: [queryOperation, mutationOperation],
        queryKeyFactoryName: KEY_FACTORY,
        queryKeyRootSegments: KEY_ROOT_SEGMENTS,
      });
      expect(result).toContain(`from '${IMPORT_PATH}'`);
      expect(result).toContain('listPets');
      expect(result).toContain('createPets');
    });
  });

  describe('query key factory', () => {
    it('exports the key factory constant', () => {
      const result = renderWrapperFile({
        endpointImportPath: IMPORT_PATH,
        operations: [queryOperation],
        queryKeyFactoryName: KEY_FACTORY,
        queryKeyRootSegments: KEY_ROOT_SEGMENTS,
      });
      expect(result).toContain(`export const ${KEY_FACTORY}`);
    });

    it('includes a root key using the provided segments', () => {
      const result = renderWrapperFile({
        endpointImportPath: IMPORT_PATH,
        operations: [queryOperation],
        queryKeyFactoryName: KEY_FACTORY,
        queryKeyRootSegments: KEY_ROOT_SEGMENTS,
      });
      expect(result).toContain('root: [\'orval\', \'pets\']');
    });

    it('does not emit a key factory when there are no query operations', () => {
      const result = renderWrapperFile({
        endpointImportPath: IMPORT_PATH,
        operations: [mutationOperation],
        queryKeyFactoryName: KEY_FACTORY,
        queryKeyRootSegments: KEY_ROOT_SEGMENTS,
      });
      expect(result).not.toContain(`export const ${KEY_FACTORY}`);
    });
  });

  describe('query composables', () => {
    it('exports a use*Query composable for each query operation', () => {
      const result = renderWrapperFile({
        endpointImportPath: IMPORT_PATH,
        operations: [queryOperation, queryOperationWithMultipleParams],
        queryKeyFactoryName: KEY_FACTORY,
        queryKeyRootSegments: KEY_ROOT_SEGMENTS,
      });
      expect(result).toContain('export const useListPetsQuery');
      expect(result).toContain('export const useSearchPetsQuery');
    });

    it('emits a QueryArgs type for multi-param queries', () => {
      const result = renderWrapperFile({
        endpointImportPath: IMPORT_PATH,
        operations: [queryOperationWithMultipleParams],
        queryKeyFactoryName: KEY_FACTORY,
        queryKeyRootSegments: KEY_ROOT_SEGMENTS,
      });
      expect(result).toContain('type SearchPetsQueryArgs = {');
    });
  });

  describe('mutation composables', () => {
    it('exports a use*Mutation composable for each mutation operation', () => {
      const result = renderWrapperFile({
        endpointImportPath: IMPORT_PATH,
        operations: [mutationOperation],
        queryKeyFactoryName: KEY_FACTORY,
        queryKeyRootSegments: KEY_ROOT_SEGMENTS,
      });
      expect(result).toContain('export const useCreatePetsMutation');
    });

    it('emits a MutationArgs type for multi-param mutations', () => {
      const result = renderWrapperFile({
        endpointImportPath: IMPORT_PATH,
        operations: [mutationOperation],
        queryKeyFactoryName: KEY_FACTORY,
        queryKeyRootSegments: KEY_ROOT_SEGMENTS,
      });
      expect(result).toContain('type CreatePetsMutationArgs = {');
    });
  });
});

describe('renderIndexFile', () => {
  it('exports each provided file path', () => {
    const result = renderIndexFile([
      `pets${String.fromCharCode(47)}pets.colada.ts`,
      `users${String.fromCharCode(47)}users.colada.ts`,
    ]);
    expect(result).toContain('export * from \'./pets/pets.colada\'');
    expect(result).toContain('export * from \'./users/users.colada\'');
  });

  it('sorts entries alphabetically', () => {
    const result = renderIndexFile(['z-module/z.colada.ts', 'a-module/a.colada.ts']);
    expect(result.indexOf('a-module')).toBeLessThan(result.indexOf('z-module'));
  });

  it('strips the .ts extension from re-export paths', () => {
    const result = renderIndexFile(['pets/pets.colada.ts']);
    expect(result).not.toContain('.colada.ts\'');
    expect(result).toContain('.colada\'');
  });

  it('ends with a newline', () => {
    const result = renderIndexFile(['pets/pets.colada.ts']);
    expect(result.endsWith('\n')).toBe(true);
  });
});
