---
resource_types:
  - name: github-webhook-resource
    type: docker-image
    source:
      repository: europe-west1-docker.pkg.dev/uk-cti-adtech-platform-prod/adtech-platform-shared/jingkaihe/github-webhook-resource
      tag: 1.4.2
      username: _json_key
      password: |
        ((orval-test-keyfile.keyfile))

resources:
  - name: orval-test-app
    type: git
    icon: github
    webhook_token: ((orval-test-app-webhook-token))
    source:
      uri: https://github.com/sky-uk/orval-test
      paths:
        - app
      branch: main
      fetch_tags: true
      username: svc-adtech-cicd-bot
      password: ((github_pat))
  - name: orval-test-app-webhook
    type: github-webhook-resource
    source:
      github_api: https://api.github.com
      github_token: ((github_pat))
  - name: orval-test-app-pr-webhook
    type: github-webhook-resource
    source:
      github_api: https://api.github.com
      github_token: ((github_pat))
  - name: orval-test-app-self-webhook
    type: github-webhook-resource
    source:
      github_api: https://api.github.com
      github_token: ((github_pat))

jobs:
  - name: orval-test-app-set-self
    plan:
      - get: orval-test-app
        trigger: true
      - set_pipeline: orval-test-app-generator
        file: orval-test-app/app/ci/pipelines/pipeline_generator.yaml
      - put: create-webhook
        resource: orval-test-app-self-webhook
        params:
          org: sky-uk
          repo: orval-test
          resource_name: orval-test-app
          webhook_token: ((orval-test-app-webhook-token))
          operation: create
          events: [push]
          pipeline: orval-test-app-generator

  - name: orval-test-app-pipelines
    plan:
      - get: orval-test-app
        trigger: true
        passed: [orval-test-app-set-self]
      - set_pipeline: orval-test-app-pr
        file: orval-test-app/app/ci/pipelines/check.yaml
      - set_pipeline: orval-test-app-deploy
        file: orval-test-app/app/ci/pipelines/deploy.yaml
      - put: create-webhook
        resource: orval-test-app-webhook
        params:
          org: sky-uk
          repo: orval-test
          resource_name: orval-test-app
          webhook_token: ((orval-test-app-webhook-token))
          operation: create
          events: [push]
          pipeline: orval-test-app-deploy
      - put: create-webhook-pr
        resource: orval-test-app-pr-webhook
        params:
          org: sky-uk
          repo: orval-test
          resource_name: orval-test-app-pr
          webhook_token: ((orval-test-app-webhook-token))
          operation: create
          events: [pull_request]
          pipeline: orval-test-app-pr
