---
apiVersion: v1
kind: Service
metadata:
  name: orval-test-server
spec:
  selector:
    app: orval-test-server
  ports:
    - name: server
      protocol: TCP
      port: 3000
      targetPort: 3000
