/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * orval-test API
 * API Documentation for the orval-test.
 * OpenAPI spec version: 0.0.0
 */

export type GetSession200Avatar = {
  src: string;
  alt: string;
};
