/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * orval-test API
 * API Documentation for the orval-test.
 * OpenAPI spec version: 0.0.0
 */
import type { GetSession200Avatar } from './getSession200Avatar';

export type GetSession200 = {
  email: string;
  name: string;
  company: string;
  avatar?: GetSession200Avatar;
};
