/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * orval-test API
 * API Documentation for the orval-test.
 * OpenAPI spec version: 0.0.0
 */
import type { GetUsers200ResultsItem } from './getUsers200ResultsItem';

export type GetUsers200 = {
  results: GetUsers200ResultsItem[];
  count: number;
  page: number;
  next?: string;
  previous?: string;
};
