/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * orval-test API
 * API Documentation for the orval-test.
 * OpenAPI spec version: 0.0.0
 */

export type GetUsersParams = {
/**
 * @minimum 1
 * @maximum 9007199254740991
 */
page?: number;
/**
 * @minimum 5
 * @maximum 100
 */
page_size?: number;
search?: string;
sort?: string | string[];
};
