/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary Search pets by query params
 */
export const searchPetsQueryLimitMax = 100;



export const SearchPetsQueryParams = zod.object({
  "requirednullableString": zod.string().nullable(),
  "requirednullableStringTwo": zod.string().nullable(),
  "nonRequirednullableString": zod.string().nullish(),
  "status": zod.enum(['available', 'pending', 'sold']).optional().describe('Filter by adoption status'),
  "limit": zod.number().min(1).max(searchPetsQueryLimitMax).optional().describe('Maximum number of results to return')
})


export const searchPetsResponseNameMax = 100;

export const searchPetsResponseTagMax = 50;

export const searchPetsResponseStatusDefault = `available`;
export const searchPetsResponseAgeMin = 0;
export const searchPetsResponseAgeMax = 30;

export const searchPetsResponseRatingMin = 0;
export const searchPetsResponseRatingMax = 5;
export const searchPetsResponseRatingMultipleOf = 0.5;

export const searchPetsResponsePhoneRegExp = new RegExp('^\\+?[1-9]\\d{1,14}$');


export const SearchPetsResponseItem = zod.object({
  "id": zod.number().min(1).describe('Unique identifier for the pet'),
  "name": zod.string().min(1).max(searchPetsResponseNameMax).describe('Name of the pet'),
  "tag": zod.string().min(1).max(searchPetsResponseTagMax).optional().describe('Optional classification tag'),
  "email": zod.email().optional().describe('Owner contact email'),
  "status": zod.enum(['available', 'pending', 'sold']).default(searchPetsResponseStatusDefault).describe('Current adoption status'),
  "age": zod.number().min(searchPetsResponseAgeMin).max(searchPetsResponseAgeMax).optional().describe('Age of the pet in years'),
  "rating": zod.number().min(searchPetsResponseRatingMin).max(searchPetsResponseRatingMax).multipleOf(searchPetsResponseRatingMultipleOf).optional().describe('Average customer rating'),
  "phone": zod.string().regex(searchPetsResponsePhoneRegExp).optional().describe('Contact phone in E.164 format'),
  "requiredNullableString": zod.string().nullable(),
  "optionalNullableString": zod.string().nullish()
})
export const SearchPetsResponse = zod.array(SearchPetsResponseItem).max(100)

/**
 * @summary List all pets
 */
export const ListPetsQueryParams = zod.object({
  "limit": zod.string().optional().describe('How many items to return at one time (max 100)')
})


export const listPetsResponseNameMax = 100;

export const listPetsResponseTagMax = 50;

export const listPetsResponseStatusDefault = `available`;
export const listPetsResponseAgeMin = 0;
export const listPetsResponseAgeMax = 30;

export const listPetsResponseRatingMin = 0;
export const listPetsResponseRatingMax = 5;
export const listPetsResponseRatingMultipleOf = 0.5;

export const listPetsResponsePhoneRegExp = new RegExp('^\\+?[1-9]\\d{1,14}$');


export const ListPetsResponseItem = zod.object({
  "id": zod.number().min(1).describe('Unique identifier for the pet'),
  "name": zod.string().min(1).max(listPetsResponseNameMax).describe('Name of the pet'),
  "tag": zod.string().min(1).max(listPetsResponseTagMax).optional().describe('Optional classification tag'),
  "email": zod.email().optional().describe('Owner contact email'),
  "status": zod.enum(['available', 'pending', 'sold']).default(listPetsResponseStatusDefault).describe('Current adoption status'),
  "age": zod.number().min(listPetsResponseAgeMin).max(listPetsResponseAgeMax).optional().describe('Age of the pet in years'),
  "rating": zod.number().min(listPetsResponseRatingMin).max(listPetsResponseRatingMax).multipleOf(listPetsResponseRatingMultipleOf).optional().describe('Average customer rating'),
  "phone": zod.string().regex(listPetsResponsePhoneRegExp).optional().describe('Contact phone in E.164 format'),
  "requiredNullableString": zod.string().nullable(),
  "optionalNullableString": zod.string().nullish()
})
export const ListPetsResponse = zod.array(ListPetsResponseItem).max(100)

/**
 * @summary Create a pet
 */
export const createPetsBodyNameMax = 100;

export const createPetsBodyTagMax = 50;

export const createPetsBodyStatusDefault = `available`;

export const CreatePetsBody = zod.object({
  "name": zod.string().min(1).max(createPetsBodyNameMax).describe('Name of the pet'),
  "tag": zod.string().min(1).max(createPetsBodyTagMax).describe('Classification tag'),
  "email": zod.email().optional().describe('Owner contact email'),
  "status": zod.enum(['available', 'pending', 'sold']).default(createPetsBodyStatusDefault).describe('Initial adoption status')
})

/**
 * @summary Info for a specific pet
 */
export const ShowPetByIdParams = zod.object({
  "petId": zod.string().describe('The id of the pet to retrieve')
})


export const showPetByIdResponseNameMax = 100;

export const showPetByIdResponseTagMax = 50;

export const showPetByIdResponseStatusDefault = `available`;
export const showPetByIdResponseAgeMin = 0;
export const showPetByIdResponseAgeMax = 30;

export const showPetByIdResponseRatingMin = 0;
export const showPetByIdResponseRatingMax = 5;
export const showPetByIdResponseRatingMultipleOf = 0.5;

export const showPetByIdResponsePhoneRegExp = new RegExp('^\\+?[1-9]\\d{1,14}$');


export const ShowPetByIdResponse = zod.object({
  "id": zod.number().min(1).describe('Unique identifier for the pet'),
  "name": zod.string().min(1).max(showPetByIdResponseNameMax).describe('Name of the pet'),
  "tag": zod.string().min(1).max(showPetByIdResponseTagMax).optional().describe('Optional classification tag'),
  "email": zod.email().optional().describe('Owner contact email'),
  "status": zod.enum(['available', 'pending', 'sold']).default(showPetByIdResponseStatusDefault).describe('Current adoption status'),
  "age": zod.number().min(showPetByIdResponseAgeMin).max(showPetByIdResponseAgeMax).optional().describe('Age of the pet in years'),
  "rating": zod.number().min(showPetByIdResponseRatingMin).max(showPetByIdResponseRatingMax).multipleOf(showPetByIdResponseRatingMultipleOf).optional().describe('Average customer rating'),
  "phone": zod.string().regex(showPetByIdResponsePhoneRegExp).optional().describe('Contact phone in E.164 format'),
  "requiredNullableString": zod.string().nullable(),
  "optionalNullableString": zod.string().nullish()
})

/**
 * @summary Info for a specific pet as plain text
 */
export const ShowPetTextParams = zod.object({
  "petId": zod.string().describe('The id of the pet to retrieve')
})

/**
 * Upload image of the pet.
 * @summary Uploads an image.
 */
export const UploadFileParams = zod.object({
  "petId": zod.number().describe('ID of pet to update')
})

/**
 * Download image of the pet.
 * @summary Download an image.
 */
export const DownloadFileParams = zod.object({
  "petId": zod.number().describe('ID of pet to download')
})

