/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreatePetsBody,
  Error,
  ListPetsParams,
  Pet,
  Pets,
  SearchPetsParams
} from '../../models';



export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * @summary Search pets by query params
 */
export type searchPetsResponse200 = {
  data: Pets
  status: 200
}

export type searchPetsResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200>
}

export type searchPetsResponseSuccess = (searchPetsResponse200) & {
  headers: Headers;
};
export type searchPetsResponseError = (searchPetsResponseDefault) & {
  headers: Headers;
};

export type searchPetsResponse = (searchPetsResponseSuccess | searchPetsResponseError)

export const getSearchPetsUrl = (params: SearchPetsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/search?${stringifiedParams}` : `/search`
}

export const searchPets = async (params: SearchPetsParams, options?: RequestInit): Promise<searchPetsResponse> => {
  
  const res = await fetch(getSearchPetsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: searchPetsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as searchPetsResponse
}
  

/**
 * @summary List all pets
 */
export type listPetsResponse200ApplicationJson = {
  data: Pets
  status: 200
}

export type listPetsResponse200ApplicationXml = {
  data: Pets
  status: 200
}

export type listPetsResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200>
}

export type listPetsResponseSuccess = (listPetsResponse200ApplicationJson | listPetsResponse200ApplicationXml) & {
  headers: Headers;
};
export type listPetsResponseError = (listPetsResponseDefault) & {
  headers: Headers;
};

export type listPetsResponse = (listPetsResponseSuccess | listPetsResponseError)

export const getListPetsUrl = (params?: ListPetsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/pets?${stringifiedParams}` : `/pets`
}

export const listPets = async (params?: ListPetsParams, options?: RequestInit): Promise<listPetsResponse> => {
  
  const res = await fetch(getListPetsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listPetsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listPetsResponse
}
  

/**
 * @summary Create a pet
 */
export type createPetsResponse201 = {
  data: void
  status: 201
}

export type createPetsResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 201>
}

export type createPetsResponseSuccess = (createPetsResponse201) & {
  headers: Headers;
};
export type createPetsResponseError = (createPetsResponseDefault) & {
  headers: Headers;
};

export type createPetsResponse = (createPetsResponseSuccess | createPetsResponseError)

export const getCreatePetsUrl = () => {


  

  return `/pets`
}

export const createPets = async (createPetsBody: CreatePetsBody, options?: RequestInit): Promise<createPetsResponse> => {
  
  const res = await fetch(getCreatePetsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createPetsBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createPetsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createPetsResponse
}
  

/**
 * @summary Info for a specific pet
 */
export type showPetByIdResponse200TextPlain = {
  data: string
  status: 200
}

export type showPetByIdResponse200ApplicationXml = {
  data: Pet
  status: 200
}

export type showPetByIdResponse200ApplicationJson = {
  data: Pet
  status: 200
}

export type showPetByIdResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200>
}

export type showPetByIdResponseSuccess = (showPetByIdResponse200TextPlain | showPetByIdResponse200ApplicationXml | showPetByIdResponse200ApplicationJson) & {
  headers: Headers;
};
export type showPetByIdResponseError = (showPetByIdResponseDefault) & {
  headers: Headers;
};

export type showPetByIdResponse = (showPetByIdResponseSuccess | showPetByIdResponseError)

export const getShowPetByIdUrl = (petId: string,) => {


  

  return `/pets/${petId}`
}

export const showPetById = async (petId: string, options?: RequestInit): Promise<showPetByIdResponse> => {
  
  const res = await fetch(getShowPetByIdUrl(petId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: showPetByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as showPetByIdResponse
}
  

/**
 * @summary Info for a specific pet as plain text
 */
export type showPetTextResponse200 = {
  data: string
  status: 200
}

export type showPetTextResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200>
}

export type showPetTextResponseSuccess = (showPetTextResponse200) & {
  headers: Headers;
};
export type showPetTextResponseError = (showPetTextResponseDefault) & {
  headers: Headers;
};

export type showPetTextResponse = (showPetTextResponseSuccess | showPetTextResponseError)

export const getShowPetTextUrl = (petId: string,) => {


  

  return `/pets/${petId}/text`
}

export const showPetText = async (petId: string, options?: RequestInit): Promise<showPetTextResponse> => {
  
  const res = await fetch(getShowPetTextUrl(petId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: showPetTextResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as showPetTextResponse
}
  

/**
 * Upload image of the pet.
 * @summary Uploads an image.
 */
export type uploadFileResponse200 = {
  data: void
  status: 200
}

export type uploadFileResponse400 = {
  data: void
  status: 400
}

export type uploadFileResponse404 = {
  data: void
  status: 404
}

export type uploadFileResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200 | 400 | 404>
}

export type uploadFileResponseSuccess = (uploadFileResponse200) & {
  headers: Headers;
};
export type uploadFileResponseError = (uploadFileResponse400 | uploadFileResponse404 | uploadFileResponseDefault) & {
  headers: Headers;
};

export type uploadFileResponse = (uploadFileResponseSuccess | uploadFileResponseError)

export const getUploadFileUrl = (petId: number,) => {


  

  return `/pet/${petId}/uploadImage`
}

export const uploadFile = async (petId: number,
    uploadFileBody: Blob, options?: RequestInit): Promise<uploadFileResponse> => {
  
  const res = await fetch(getUploadFileUrl(petId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/octet-stream', ...options?.headers },
    body: JSON.stringify(
      uploadFileBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: uploadFileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as uploadFileResponse
}
  

/**
 * Download image of the pet.
 * @summary Download an image.
 */
export type downloadFileResponse200 = {
  data: Blob
  status: 200
}

export type downloadFileResponse400 = {
  data: void
  status: 400
}

export type downloadFileResponse404 = {
  data: void
  status: 404
}

export type downloadFileResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200 | 400 | 404>
}

export type downloadFileResponseSuccess = (downloadFileResponse200) & {
  headers: Headers;
};
export type downloadFileResponseError = (downloadFileResponse400 | downloadFileResponse404 | downloadFileResponseDefault) & {
  headers: Headers;
};

export type downloadFileResponse = (downloadFileResponseSuccess | downloadFileResponseError)

export const getDownloadFileUrl = (petId: number,) => {


  

  return `/pet/${petId}/downloadImage`
}

export const downloadFile = async (petId: number, options?: RequestInit): Promise<downloadFileResponse> => {
  
  const res = await fetch(getDownloadFileUrl(petId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: downloadFileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as downloadFileResponse
}
  

