/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  CreatePetsBody,
  Error,
  ListPetsParams,
  Pet,
  Pets,
  SearchPetsParams
} from '../../models';





export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;


/**
 * @summary Search pets by query params
 */
export type searchPetsResponse200 = {
  data: Pets
  status: 200
}

export type searchPetsResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200>
}

export type searchPetsResponseSuccess = (searchPetsResponse200) & {
  headers: Headers;
};
export type searchPetsResponseError = (searchPetsResponseDefault) & {
  headers: Headers;
};

export type searchPetsResponse = (searchPetsResponseSuccess | searchPetsResponseError)

export const getSearchPetsUrl = (params: SearchPetsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/search?${stringifiedParams}` : `/search`
}

export const searchPets = async (params: SearchPetsParams, options?: RequestInit): Promise<searchPetsResponse> => {
  
  const res = await fetch(getSearchPetsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: searchPetsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as searchPetsResponse
}
  




export const getSearchPetsQueryKey = (params?: MaybeRef<SearchPetsParams>,) => {
    return [
    'search', ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchPetsQueryOptions = <TData = Awaited<ReturnType<typeof searchPets>>, TError = Error>(params: MaybeRef<SearchPetsParams>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof searchPets>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getSearchPetsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchPets>>> = ({ signal }) => searchPets(unref(params), { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchPets>>, TError, TData> 
}

export type SearchPetsQueryResult = NonNullable<Awaited<ReturnType<typeof searchPets>>>
export type SearchPetsQueryError = Error


/**
 * @summary Search pets by query params
 */

export function useSearchPets<TData = Awaited<ReturnType<typeof searchPets>>, TError = Error>(
 params: MaybeRef<SearchPetsParams>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof searchPets>>, TError, TData>, fetch?: RequestInit}
  
 ): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getSearchPetsQueryOptions(params,options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
}




/**
 * @summary List all pets
 */
export type listPetsResponse200ApplicationJson = {
  data: Pets
  status: 200
}

export type listPetsResponse200ApplicationXml = {
  data: Pets
  status: 200
}

export type listPetsResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200>
}

export type listPetsResponseSuccess = (listPetsResponse200ApplicationJson | listPetsResponse200ApplicationXml) & {
  headers: Headers;
};
export type listPetsResponseError = (listPetsResponseDefault) & {
  headers: Headers;
};

export type listPetsResponse = (listPetsResponseSuccess | listPetsResponseError)

export const getListPetsUrl = (params?: ListPetsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/pets?${stringifiedParams}` : `/pets`
}

export const listPets = async (params?: ListPetsParams, options?: RequestInit): Promise<listPetsResponse> => {
  
  const res = await fetch(getListPetsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listPetsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listPetsResponse
}
  




export const getListPetsQueryKey = (params?: MaybeRef<ListPetsParams>,) => {
    return [
    'pets', ...(params ? [params] : [])
    ] as const;
    }

    
export const getListPetsQueryOptions = <TData = Awaited<ReturnType<typeof listPets>>, TError = Error>(params?: MaybeRef<ListPetsParams>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPets>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getListPetsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPets>>> = ({ signal }) => listPets(unref(params), { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPets>>, TError, TData> 
}

export type ListPetsQueryResult = NonNullable<Awaited<ReturnType<typeof listPets>>>
export type ListPetsQueryError = Error


/**
 * @summary List all pets
 */

export function useListPets<TData = Awaited<ReturnType<typeof listPets>>, TError = Error>(
 params?: MaybeRef<ListPetsParams>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPets>>, TError, TData>, fetch?: RequestInit}
  
 ): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListPetsQueryOptions(params,options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
}




/**
 * @summary Create a pet
 */
export type createPetsResponse201 = {
  data: void
  status: 201
}

export type createPetsResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 201>
}

export type createPetsResponseSuccess = (createPetsResponse201) & {
  headers: Headers;
};
export type createPetsResponseError = (createPetsResponseDefault) & {
  headers: Headers;
};

export type createPetsResponse = (createPetsResponseSuccess | createPetsResponseError)

export const getCreatePetsUrl = () => {


  

  return `/pets`
}

export const createPets = async (createPetsBody: CreatePetsBody, options?: RequestInit): Promise<createPetsResponse> => {
  
  const res = await fetch(getCreatePetsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createPetsBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createPetsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createPetsResponse
}
  



export const getCreatePetsMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPets>>, TError,{data: CreatePetsBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createPets>>, TError,{data: CreatePetsBody}, TContext> => {

const mutationKey = ['createPets'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPets>>, {data: CreatePetsBody}> = (props) => {
          const {data} = props ?? {};

          return  createPets(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePetsMutationResult = NonNullable<Awaited<ReturnType<typeof createPets>>>
    export type CreatePetsMutationBody = CreatePetsBody
    export type CreatePetsMutationError = Error

    /**
 * @summary Create a pet
 */
export const useCreatePets = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPets>>, TError,{data: CreatePetsBody}, TContext>, fetch?: RequestInit}
 ): UseMutationReturnType<
        Awaited<ReturnType<typeof createPets>>,
        TError,
        {data: CreatePetsBody},
        TContext
      > => {
      return useMutation(getCreatePetsMutationOptions(options));
    }
    /**
 * @summary Info for a specific pet
 */
export type showPetByIdResponse200TextPlain = {
  data: string
  status: 200
}

export type showPetByIdResponse200ApplicationXml = {
  data: Pet
  status: 200
}

export type showPetByIdResponse200ApplicationJson = {
  data: Pet
  status: 200
}

export type showPetByIdResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200>
}

export type showPetByIdResponseSuccess = (showPetByIdResponse200TextPlain | showPetByIdResponse200ApplicationXml | showPetByIdResponse200ApplicationJson) & {
  headers: Headers;
};
export type showPetByIdResponseError = (showPetByIdResponseDefault) & {
  headers: Headers;
};

export type showPetByIdResponse = (showPetByIdResponseSuccess | showPetByIdResponseError)

export const getShowPetByIdUrl = (petId: string,) => {


  

  return `/pets/${petId}`
}

export const showPetById = async (petId: string, options?: RequestInit): Promise<showPetByIdResponse> => {
  
  const res = await fetch(getShowPetByIdUrl(petId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: showPetByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as showPetByIdResponse
}
  




export const getShowPetByIdQueryKey = (petId: MaybeRef<string>,) => {
    return [
    'pets',petId
    ] as const;
    }

    
export const getShowPetByIdQueryOptions = <TData = Awaited<ReturnType<typeof showPetById>>, TError = Error>(petId: MaybeRef<string>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof showPetById>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getShowPetByIdQueryKey(petId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof showPetById>>> = ({ signal }) => showPetById(unref(petId), { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(petId))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof showPetById>>, TError, TData> 
}

export type ShowPetByIdQueryResult = NonNullable<Awaited<ReturnType<typeof showPetById>>>
export type ShowPetByIdQueryError = Error


/**
 * @summary Info for a specific pet
 */

export function useShowPetById<TData = Awaited<ReturnType<typeof showPetById>>, TError = Error>(
 petId: MaybeRef<string>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof showPetById>>, TError, TData>, fetch?: RequestInit}
  
 ): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getShowPetByIdQueryOptions(petId,options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
}




/**
 * @summary Info for a specific pet as plain text
 */
export type showPetTextResponse200 = {
  data: string
  status: 200
}

export type showPetTextResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200>
}

export type showPetTextResponseSuccess = (showPetTextResponse200) & {
  headers: Headers;
};
export type showPetTextResponseError = (showPetTextResponseDefault) & {
  headers: Headers;
};

export type showPetTextResponse = (showPetTextResponseSuccess | showPetTextResponseError)

export const getShowPetTextUrl = (petId: string,) => {


  

  return `/pets/${petId}/text`
}

export const showPetText = async (petId: string, options?: RequestInit): Promise<showPetTextResponse> => {
  
  const res = await fetch(getShowPetTextUrl(petId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: showPetTextResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as showPetTextResponse
}
  




export const getShowPetTextQueryKey = (petId: MaybeRef<string>,) => {
    return [
    'pets',petId,'text'
    ] as const;
    }

    
export const getShowPetTextQueryOptions = <TData = Awaited<ReturnType<typeof showPetText>>, TError = Error>(petId: MaybeRef<string>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof showPetText>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getShowPetTextQueryKey(petId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof showPetText>>> = ({ signal }) => showPetText(unref(petId), { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(petId))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof showPetText>>, TError, TData> 
}

export type ShowPetTextQueryResult = NonNullable<Awaited<ReturnType<typeof showPetText>>>
export type ShowPetTextQueryError = Error


/**
 * @summary Info for a specific pet as plain text
 */

export function useShowPetText<TData = Awaited<ReturnType<typeof showPetText>>, TError = Error>(
 petId: MaybeRef<string>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof showPetText>>, TError, TData>, fetch?: RequestInit}
  
 ): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getShowPetTextQueryOptions(petId,options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
}




/**
 * Upload image of the pet.
 * @summary Uploads an image.
 */
export type uploadFileResponse200 = {
  data: void
  status: 200
}

export type uploadFileResponse400 = {
  data: void
  status: 400
}

export type uploadFileResponse404 = {
  data: void
  status: 404
}

export type uploadFileResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200 | 400 | 404>
}

export type uploadFileResponseSuccess = (uploadFileResponse200) & {
  headers: Headers;
};
export type uploadFileResponseError = (uploadFileResponse400 | uploadFileResponse404 | uploadFileResponseDefault) & {
  headers: Headers;
};

export type uploadFileResponse = (uploadFileResponseSuccess | uploadFileResponseError)

export const getUploadFileUrl = (petId: number,) => {


  

  return `/pet/${petId}/uploadImage`
}

export const uploadFile = async (petId: number,
    uploadFileBody: Blob, options?: RequestInit): Promise<uploadFileResponse> => {
  
  const res = await fetch(getUploadFileUrl(petId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/octet-stream', ...options?.headers },
    body: JSON.stringify(
      uploadFileBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: uploadFileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as uploadFileResponse
}
  



export const getUploadFileMutationOptions = <TError = void | Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadFile>>, TError,{petId: number;data: Blob}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof uploadFile>>, TError,{petId: number;data: Blob}, TContext> => {

const mutationKey = ['uploadFile'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadFile>>, {petId: number;data: Blob}> = (props) => {
          const {petId,data} = props ?? {};

          return  uploadFile(petId,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UploadFileMutationResult = NonNullable<Awaited<ReturnType<typeof uploadFile>>>
    export type UploadFileMutationBody = Blob
    export type UploadFileMutationError = void | Error

    /**
 * @summary Uploads an image.
 */
export const useUploadFile = <TError = void | Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadFile>>, TError,{petId: number;data: Blob}, TContext>, fetch?: RequestInit}
 ): UseMutationReturnType<
        Awaited<ReturnType<typeof uploadFile>>,
        TError,
        {petId: number;data: Blob},
        TContext
      > => {
      return useMutation(getUploadFileMutationOptions(options));
    }
    /**
 * Download image of the pet.
 * @summary Download an image.
 */
export type downloadFileResponse200 = {
  data: Blob
  status: 200
}

export type downloadFileResponse400 = {
  data: void
  status: 400
}

export type downloadFileResponse404 = {
  data: void
  status: 404
}

export type downloadFileResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200 | 400 | 404>
}

export type downloadFileResponseSuccess = (downloadFileResponse200) & {
  headers: Headers;
};
export type downloadFileResponseError = (downloadFileResponse400 | downloadFileResponse404 | downloadFileResponseDefault) & {
  headers: Headers;
};

export type downloadFileResponse = (downloadFileResponseSuccess | downloadFileResponseError)

export const getDownloadFileUrl = (petId: number,) => {


  

  return `/pet/${petId}/downloadImage`
}

export const downloadFile = async (petId: number, options?: RequestInit): Promise<downloadFileResponse> => {
  
  const res = await fetch(getDownloadFileUrl(petId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: downloadFileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as downloadFileResponse
}
  




export const getDownloadFileQueryKey = (petId: MaybeRef<number>,) => {
    return [
    'pet',petId,'downloadImage'
    ] as const;
    }

    
export const getDownloadFileQueryOptions = <TData = Awaited<ReturnType<typeof downloadFile>>, TError = void | Error>(petId: MaybeRef<number>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getDownloadFileQueryKey(petId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadFile>>> = ({ signal }) => downloadFile(unref(petId), { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(petId))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData> 
}

export type DownloadFileQueryResult = NonNullable<Awaited<ReturnType<typeof downloadFile>>>
export type DownloadFileQueryError = void | Error


/**
 * @summary Download an image.
 */

export function useDownloadFile<TData = Awaited<ReturnType<typeof downloadFile>>, TError = void | Error>(
 petId: MaybeRef<number>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>, fetch?: RequestInit}
  
 ): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getDownloadFileQueryOptions(petId,options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
}




