import type { RenderEndpointImportsInput, RenderQueryArgTypesInput, RenderQueryComposableInput, RenderQueryKeyFactoryInput, RenderRuntimeImportsInput, RenderTypeImportsInput, RenderWrapperFileInput } from './types';
import { pascalCase } from './helpers';
import { generateMutationComposable } from './mutation-templates';
import {
  generateQueryCommentBlock,
  generateQueryWithEq1Param,
  generateQueryWithGt1Params,
  generateQueryWithNoParams,
  getQueryKeyFactoryCall,
} from './query-templates';

/**
 * Renders the generated-file header comment.
 */
const renderFileHeader = (): string => {
  return `/**
 * Generated by orval/generate-colada-wrappers.ts
 * Do not edit manually.
 */`;
};

/**
 * Renders type-only imports required by query composables.
 * @param {RenderTypeImportsInput} input Function input.
 * @param {boolean} input.hasQueryOperations Whether query operations exist.
 */
const renderTypeImports = ({ hasQueryOperations }: RenderTypeImportsInput): string => {
  return hasQueryOperations ? `import type { UseQueryOptions } from '@pinia/colada';` : '';
};

/**
 * Renders runtime imports based on which composable kinds are present.
 * @param {RenderRuntimeImportsInput} input Function input.
 * @param {boolean} input.hasQueryOperations Whether query operations exist.
 * @param {boolean} input.hasMutationOperations Whether mutation operations exist.
 */
const renderRuntimeImports = ({ hasQueryOperations, hasMutationOperations }: RenderRuntimeImportsInput): string => {
  if (hasQueryOperations && hasMutationOperations) {
    return `import { useMutation, useQuery } from '@pinia/colada';`;
  }

  if (hasQueryOperations) {
    return `import { useQuery } from '@pinia/colada';`;
  }

  return `import { useMutation } from '@pinia/colada';`;
};

/**
 * Renders endpoint operation imports sorted alphabetically for stable output.
 * @param {RenderEndpointImportsInput} input Function input.
 * @param {string} input.endpointImportPath Endpoint module import path.
 * @param {ParsedOperation[]} input.operations Parsed operations to import.
 */
const renderEndpointImports = ({ endpointImportPath, operations }: RenderEndpointImportsInput): string => {
  const sortedOperationNames = operations
    .map((operation) => operation.name)
    .sort((a, b) => a.localeCompare(b));

  return `import { ${sortedOperationNames.join(', ')} } from '${endpointImportPath}';`;
};

/**
 * Renders query argument object types for operations with more than one parameter.
 * @param {RenderQueryArgTypesInput} input Function input.
 * @param {ParsedOperation[]} input.queryOperations Query operations to analyze.
 */
const renderQueryArgTypes = ({ queryOperations }: RenderQueryArgTypesInput): string => {
  return queryOperations
    .filter((operation) => operation.params.length > 1)
    .map((operation) => {
      const queryArgsTypeName = `${pascalCase(operation.name)}QueryArgs`;
      const fields = operation.params
        .map((param, index) => `  ${param.name}${param.optional ? '?' : ''}: Parameters<typeof ${operation.name}>[${index}];`)
        .join('\n');

      return `type ${queryArgsTypeName} = {\n${fields}\n};`;
    })
    .join('\n\n');
};

/**
 * Renders a reusable query key factory object used by generated query composables.
 * @param {RenderQueryKeyFactoryInput} input Function input.
 * @param {ParsedOperation[]} input.queryOperations Query operations to include.
 * @param {string} input.queryKeyFactoryName Query key factory object name.
 * @param {string[]} input.queryKeyRootSegments Root key path segments.
 */
const renderQueryKeyFactory = ({ queryOperations, queryKeyFactoryName, queryKeyRootSegments }: RenderQueryKeyFactoryInput): string => {
  if (queryOperations.length === 0) {
    return '';
  }

  const rootKeyParts = ['orval', ...queryKeyRootSegments].map((part) => `'${part}'`).join(', ');
  const entries = queryOperations
    .map((operation) => {
      if (operation.params.length > 1) {
        const queryArgsTypeName = `${pascalCase(operation.name)}QueryArgs`;
        return `  ${operation.name}: (params: ${queryArgsTypeName}) => [...${queryKeyFactoryName}.root, '${operation.name}', params.${operation.params[0].name} ?? null] as const,`;
      }

      if (operation.params.length === 1) {
        const [param] = operation.params;
        return `  ${operation.name}: (${param.name}: Parameters<typeof ${operation.name}>[0]) => [...${queryKeyFactoryName}.root, '${operation.name}', ${param.name} ?? null] as const,`;
      }

      return `  ${operation.name}: () => [...${queryKeyFactoryName}.root, '${operation.name}'] as const,`;
    })
    .join('\n');

  return `export const ${queryKeyFactoryName} = {\n  root: [${rootKeyParts}] as const,\n${entries}\n};`;
};

/**
 * Renders one query composable implementation for the provided operation.
 * @param {RenderQueryComposableInput} input Function input.
 * @param {ParsedOperation} input.operation Parsed query operation metadata.
 * @param {string} input.queryKeyFactoryName Query key factory object name.
 */
const renderQueryComposable = ({ operation, queryKeyFactoryName }: RenderQueryComposableInput): string => {
  const wrapperName = `use${pascalCase(operation.name)}Query`;
  const keyFactoryCall = getQueryKeyFactoryCall({ operation, queryKeyFactoryName });
  const commentBlock = generateQueryCommentBlock({
    operation,
    operationName: operation.name,
    keyFactoryCall,
    queryKeyFactoryName,
  });

  if (operation.params.length > 1) {
    return generateQueryWithGt1Params({
      commentBlock,
      operationName: operation.name,
      operationParams: operation.params,
      wrapperName,
      queryKeyFactoryName,
    });
  }

  if (operation.params.length === 1) {
    return generateQueryWithEq1Param({
      commentBlock,
      operationName: operation.name,
      paramName: operation.params[0].name,
      wrapperName,
      queryKeyFactoryName,
    });
  }

  return generateQueryWithNoParams({
    commentBlock,
    operationName: operation.name,
    wrapperName,
    queryKeyFactoryName,
  });
};

/**
 * Renders a complete generated composable wrapper file for one endpoint module.
 * @param {RenderWrapperFileInput} input Function input.
 * @param {string} input.endpointImportPath Endpoint module import path.
 * @param {ParsedOperation[]} input.operations Parsed operations.
 * @param {string} input.queryKeyFactoryName Query key factory object name.
 * @param {string[]} input.queryKeyRootSegments Root key path segments.
 */
export const renderWrapperFile = ({
  endpointImportPath,
  operations,
  queryKeyFactoryName,
  queryKeyRootSegments,
}: RenderWrapperFileInput): string => {
  const queryOperations = operations.filter((operation) => operation.kind === 'query');
  const mutationOperations = operations.filter((operation) => operation.kind === 'mutation');
  const hasQueryOperations = queryOperations.length > 0;
  const hasMutationOperations = mutationOperations.length > 0;

  const content = [
    renderFileHeader(),
    renderTypeImports({ hasQueryOperations }),
    renderRuntimeImports({ hasQueryOperations, hasMutationOperations }),
    renderEndpointImports({ endpointImportPath, operations }),
    renderQueryArgTypes({ queryOperations }),
    renderQueryKeyFactory({ queryOperations, queryKeyFactoryName, queryKeyRootSegments }),
    queryOperations.map((operation) => renderQueryComposable({ operation, queryKeyFactoryName })).join('\n\n'),
    mutationOperations.map((operation) => generateMutationComposable({ operation, queryKeyFactoryName })).join('\n\n'),
  ]
    .filter((section) => section.length > 0)
    .join('\n\n');

  return `${content}\n`;
};

/**
 * Renders the generated barrel export file for all composable wrapper files.
 * @param {string[]} entries Relative file paths to export.
 */
export const renderIndexFile = (entries: string[]): string => {
  const exports = entries
    .sort((a, b) => a.localeCompare(b))
    .map((entry) => `export * from './${entry.replace(/\\/g, '/').replace(/\.ts$/, '')}';`)
    .join('\n');

  return `${exports}\n`;
};
