---
resource_types:
  - name: github-webhook-resource
    type: docker-image
    source:
      repository: europe-west1-docker.pkg.dev/uk-cti-adtech-platform-prod/adtech-platform-shared/jingkaihe/github-webhook-resource
      tag: 1.4.2
      username: _json_key
      password: |
        ((orval-test-keyfile.keyfile))

resources:
  - name: orval-test-server
    type: git
    icon: github
    webhook_token: ((orval-test-server-webhook-token))
    source:
      uri: https://github.com/sky-uk/orval-test
      paths:
        - server
      branch: main
      fetch_tags: true
      username: svc-adtech-cicd-bot
      password: ((github_pat))
  - name: orval-test-server-webhook
    type: github-webhook-resource
    source:
      github_api: https://api.github.com
      github_token: ((github_pat))
  - name: orval-test-server-pr-webhook
    type: github-webhook-resource
    source:
      github_api: https://api.github.com
      github_token: ((github_pat))
  - name: orval-test-server-self-webhook
    type: github-webhook-resource
    source:
      github_api: https://api.github.com
      github_token: ((github_pat))

jobs:
  - name: orval-test-server-set-self
    plan:
      - get: orval-test-server
        trigger: true
      - set_pipeline: orval-test-server-generator
        file: orval-test-server/server/ci/pipelines/pipeline_generator.yaml
      - put: create-webhook
        resource: orval-test-server-self-webhook
        params:
          org: sky-uk
          repo: orval-test
          resource_name: orval-test-server
          webhook_token: ((orval-test-server-webhook-token))
          operation: create
          events: [push]
          pipeline: orval-test-server-generator

  - name: orval-test-server-pipelines
    plan:
      - get: orval-test-server
        trigger: true
        passed: [orval-test-server-set-self]
      - set_pipeline: orval-test-server-pr
        file: orval-test-server/server/ci/pipelines/check.yaml
      - set_pipeline: orval-test-server-deploy
        file: orval-test-server/server/ci/pipelines/deploy.yaml
      - put: create-webhook
        resource: orval-test-server-webhook
        params:
          org: sky-uk
          repo: orval-test
          resource_name: orval-test-server
          webhook_token: ((orval-test-server-webhook-token))
          operation: create
          events: [push]
          pipeline: orval-test-server-deploy
      - put: create-webhook-pr
        resource: orval-test-server-pr-webhook
        params:
          org: sky-uk
          repo: orval-test
          resource_name: orval-test-server-pr
          webhook_token: ((orval-test-server-webhook-token))
          operation: create
          events: [pull_request]
          pipeline: orval-test-server-pr
