/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * orval-test API
 * API Documentation for the orval-test.
 * OpenAPI spec version: 0.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  DeleteUsersId200,
  GetUsers200,
  GetUsersId200,
  PatchUsersId200,
  PostUsers201
} from '../../models';


export const getGetUsersResponseMock = (overrideResponse: Partial<Extract<GetUsers200, object>> = {}): GetUsers200 => ({results: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.number.float({fractionDigits: 2}), name: faker.string.alpha({length: {min: 10, max: 20}}), jobTitle: faker.string.alpha({length: {min: 10, max: 20}})})), count: faker.number.float({fractionDigits: 2}), page: faker.number.float({fractionDigits: 2}), next: faker.helpers.arrayElement([faker.internet.url(), undefined]), previous: faker.helpers.arrayElement([faker.internet.url(), undefined]), ...overrideResponse})

export const getPostUsersResponseMock = (overrideResponse: Partial<Extract<PostUsers201, object>> = {}): PostUsers201 => ({id: faker.number.float({fractionDigits: 2}), name: faker.string.alpha({length: {min: 10, max: 20}}), jobTitle: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getGetUsersIdResponseMock = (overrideResponse: Partial<Extract<GetUsersId200, object>> = {}): GetUsersId200 => ({id: faker.number.float({fractionDigits: 2}), name: faker.string.alpha({length: {min: 10, max: 20}}), jobTitle: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getPatchUsersIdResponseMock = (overrideResponse: Partial<Extract<PatchUsersId200, object>> = {}): PatchUsersId200 => ({id: faker.number.float({fractionDigits: 2}), name: faker.string.alpha({length: {min: 10, max: 20}}), jobTitle: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getDeleteUsersIdResponseMock = (overrideResponse: Partial<Extract<DeleteUsersId200, object>> = {}): DeleteUsersId200 => ({id: faker.number.float({fractionDigits: 2}), ...overrideResponse})


export const getGetUsersMockHandler = (overrideResponse?: GetUsers200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetUsers200> | GetUsers200), options?: RequestHandlerOptions) => {
  return http.get('*/users', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetUsersResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostUsersMockHandler = (overrideResponse?: PostUsers201 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PostUsers201> | PostUsers201), options?: RequestHandlerOptions) => {
  return http.post('*/users', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostUsersResponseMock(),
      { status: 201
      })
  }, options)
}

export const getGetUsersIdMockHandler = (overrideResponse?: GetUsersId200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetUsersId200> | GetUsersId200), options?: RequestHandlerOptions) => {
  return http.get('*/users/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetUsersIdResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPatchUsersIdMockHandler = (overrideResponse?: PatchUsersId200 | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<PatchUsersId200> | PatchUsersId200), options?: RequestHandlerOptions) => {
  return http.patch('*/users/:id', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPatchUsersIdResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeleteUsersIdMockHandler = (overrideResponse?: DeleteUsersId200 | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<DeleteUsersId200> | DeleteUsersId200), options?: RequestHandlerOptions) => {
  return http.delete('*/users/:id', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeleteUsersIdResponseMock(),
      { status: 200
      })
  }, options)
}
export const getUsersMock = () => [
  getGetUsersMockHandler(),
  getPostUsersMockHandler(),
  getGetUsersIdMockHandler(),
  getPatchUsersIdMockHandler(),
  getDeleteUsersIdMockHandler()
]
