/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * orval-test API
 * API Documentation for the orval-test.
 * OpenAPI spec version: 0.0.0
 */
import type {
  DeleteUsersId200,
  GetUsers200,
  GetUsersId200,
  GetUsersParams,
  PatchUsersId200,
  PatchUsersIdBody,
  PostUsers201,
  PostUsersBody
} from '../../models';

import { customInstance } from '../../mutator/custom-instance';

/**
 * Get list of users
 */
export type getUsersResponse200 = {
  data: GetUsers200
  status: 200
}

export type getUsersResponseSuccess = (getUsersResponse200) & {
  headers: Headers;
};
;

export type getUsersResponse = (getUsersResponseSuccess)

export const getGetUsersUrl = (params?: GetUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3000/users?${stringifiedParams}` : `http://localhost:3000/users`
}

export const getUsers = async (params?: GetUsersParams, options?: RequestInit): Promise<getUsersResponse> => {
  
  return customInstance<getUsersResponse>(getGetUsersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Create a new user
 */
export type postUsersResponse201 = {
  data: PostUsers201
  status: 201
}

export type postUsersResponse400 = {
  data: void
  status: 400
}

export type postUsersResponseSuccess = (postUsersResponse201) & {
  headers: Headers;
};
export type postUsersResponseError = (postUsersResponse400) & {
  headers: Headers;
};

export type postUsersResponse = (postUsersResponseSuccess | postUsersResponseError)

export const getPostUsersUrl = () => {


  

  return `http://localhost:3000/users`
}

export const postUsers = async (postUsersBody: PostUsersBody, options?: RequestInit): Promise<postUsersResponse> => {
  
  return customInstance<postUsersResponse>(getPostUsersUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postUsersBody,)
  }
);}
  

/**
 * Get user by ID
 */
export type getUsersIdResponse200 = {
  data: GetUsersId200
  status: 200
}

export type getUsersIdResponse404 = {
  data: void
  status: 404
}

export type getUsersIdResponseSuccess = (getUsersIdResponse200) & {
  headers: Headers;
};
export type getUsersIdResponseError = (getUsersIdResponse404) & {
  headers: Headers;
};

export type getUsersIdResponse = (getUsersIdResponseSuccess | getUsersIdResponseError)

export const getGetUsersIdUrl = (id: number,) => {


  

  return `http://localhost:3000/users/${id}`
}

export const getUsersId = async (id: number, options?: RequestInit): Promise<getUsersIdResponse> => {
  
  return customInstance<getUsersIdResponse>(getGetUsersIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Update user by ID
 */
export type patchUsersIdResponse200 = {
  data: PatchUsersId200
  status: 200
}

export type patchUsersIdResponse400 = {
  data: void
  status: 400
}

export type patchUsersIdResponse404 = {
  data: void
  status: 404
}

export type patchUsersIdResponseSuccess = (patchUsersIdResponse200) & {
  headers: Headers;
};
export type patchUsersIdResponseError = (patchUsersIdResponse400 | patchUsersIdResponse404) & {
  headers: Headers;
};

export type patchUsersIdResponse = (patchUsersIdResponseSuccess | patchUsersIdResponseError)

export const getPatchUsersIdUrl = (id: number,) => {


  

  return `http://localhost:3000/users/${id}`
}

export const patchUsersId = async (id: number,
    patchUsersIdBody: PatchUsersIdBody, options?: RequestInit): Promise<patchUsersIdResponse> => {
  
  return customInstance<patchUsersIdResponse>(getPatchUsersIdUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      patchUsersIdBody,)
  }
);}
  

/**
 * Delete user by ID
 */
export type deleteUsersIdResponse200 = {
  data: DeleteUsersId200
  status: 200
}

export type deleteUsersIdResponse404 = {
  data: void
  status: 404
}

export type deleteUsersIdResponseSuccess = (deleteUsersIdResponse200) & {
  headers: Headers;
};
export type deleteUsersIdResponseError = (deleteUsersIdResponse404) & {
  headers: Headers;
};

export type deleteUsersIdResponse = (deleteUsersIdResponseSuccess | deleteUsersIdResponseError)

export const getDeleteUsersIdUrl = (id: number,) => {


  

  return `http://localhost:3000/users/${id}`
}

export const deleteUsersId = async (id: number, options?: RequestInit): Promise<deleteUsersIdResponse> => {
  
  return customInstance<deleteUsersIdResponse>(getDeleteUsersIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

