/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * orval-test API
 * API Documentation for the orval-test.
 * OpenAPI spec version: 0.0.0
 */
import * as zod from 'zod';


/**
 * Get list of users
 */
export const getUsersQueryPageMax = 9007199254740991;

export const getUsersQueryPageSizeMin = 5;
export const getUsersQueryPageSizeMax = 100;



export const GetUsersQueryParams = zod.object({
  "page": zod.number().min(1).max(getUsersQueryPageMax).optional(),
  "page_size": zod.number().min(getUsersQueryPageSizeMin).max(getUsersQueryPageSizeMax).optional(),
  "search": zod.string().optional(),
  "sort": zod.union([zod.string(),zod.array(zod.string())]).optional()
})

export const GetUsersResponse = zod.object({
  "results": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "jobTitle": zod.string()
})),
  "count": zod.number(),
  "page": zod.number(),
  "next": zod.url().optional(),
  "previous": zod.url().optional()
})

/**
 * Create a new user
 */
export const PostUsersBody = zod.object({
  "name": zod.string(),
  "jobTitle": zod.string()
})

/**
 * Get user by ID
 */
export const GetUsersIdParams = zod.object({
  "id": zod.number()
})

export const GetUsersIdResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "jobTitle": zod.string()
})

/**
 * Update user by ID
 */
export const PatchUsersIdParams = zod.object({
  "id": zod.number()
})

export const PatchUsersIdBody = zod.object({
  "name": zod.string(),
  "jobTitle": zod.string()
})

export const PatchUsersIdResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "jobTitle": zod.string()
})

/**
 * Delete user by ID
 */
export const DeleteUsersIdParams = zod.object({
  "id": zod.number()
})

export const DeleteUsersIdResponse = zod.object({
  "id": zod.number()
})

